### ISSUE TITLE
Allow free members to download

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/RCP-Download-Monitor-Bridge#3]
Right now only paid subscribers can download files restricted to "Members only", due to us checking access with `rcp_is_active()` here: https://github.com/restrictcontentpro/RCP-Download-Monitor-Bridge/blob/1.0.2/rcp-download-monitor.php#L67

I've seen at least a few tickets now about free subscribers not being able to download files. I think we should change this check to include `free` status members.

We could do this when we do #2, or before then.

**Comment by pippinsplugins** [comment]
It would be cool to update this plugin to offer the same restriction options as core an then leverage the `can_access()` method of `RCP_Member`.

**Comment by mindctrl** [comment]
Agreed.

**Comment by nosegraze** [comment]
Added a PR here: #4 that fixes this and #2 . 

- I added the whole meta box to the CPT, which will work after this gets merged: https://github.com/restrictcontentpro/restrict-content-pro/issues/861
- The downside is that we have some items in the meta box that are kind of irrelevant to this CPT (hide excerpt and from RSS feeds).
- If they're using RCP lower than 2.7 then it defaults back to the old restriction check, but I added support there for free members to fix this issue.

**Comment by mindctrl** [comment]
@nosegraze this works well in my tests.

re: irrelevant excerpt/RSS options, since we're allowing post types to be filtered, maybe we should consider a filter in `metabox-view.php` for controlling the output of the additional options.

The old setting box still shows on the right side. Do we need it in 2.7+?

**Comment by nosegraze** [comment]
I like the idea of a filter in `metabox-view.php`.

The "is member" thing is actually built into DLM rather than this add-on. So as of 2.7 they would work totally independently of each other and the "is member" checkbox would limit the download to anyone who's logged in to an account, regardless of RCP settings.

**Comment by pippinsplugins** [comment]
This looks good to me.

>>>The old setting box still shows on the right side. Do we need it in 2.7+?

I wouldn't think there's any reason for iyt.

**Comment by mindctrl** [comment]
> The "is member" thing is actually built into DLM rather than this add-on. 

Ah yes, forgot about that.
